simplemooc/courses/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    #re_path(r'^(?P<pk>\d+)/$', views.details, name='details'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
    re_path(r'^(?P<slug>[\w_-]+)/inscricao$', views.enrollment, name='enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/cancelar_inscricao$', views.undo_enrollment, 
        name='undo_enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios$', views.announcements, name='announcements'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$', views.show_announcement, name='show_announcement'),
    re_path(r'^(?P<slug>[\w_-]+)/aulas/$', views.lessons, name='lessons'),
    re_path(r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$', views.lesson, name='lesson'),
    re_path(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simplemooc.core.urls') ),
    path('cursos/', include('simplemooc.courses.urls') ),
    path('conta/', include('simplemooc.accounts.urls')),
    path('forum/', include('simplemooc.forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT  )

simplemooc/courses/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone

from simplemooc.core.mail import send_mail_template

class CourseManager(models.Manager):
    
    def search(self, query): #realiza busca com base na string de entrada
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | 
            models.Q(description__icontains=query) )

class Courses(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descricao simples', blank=True, max_length=80)
    about = models.TextField('Sobre o curso', blank=True)
    start_date = models.DateField('Data de Inicio', null=True, blank=True)
    image = models.ImageField(upload_to='courses/images', verbose_name='Imagem',
        null=True, blank=True)
    created_at = models.DateTimeField('Criado em:',auto_now_add=True )
    updated_at = models.DateTimeField('Atualizado em:',auto_now=True )

    objects = CourseManager()

    def get_absolute_url(self):
        #return ('courses:details', (), {'slug': self.slug} )
        return reverse('courses:details',args=[self.slug] )

    #href="{% url 'courses:details' course.slug %}"
    #<a href="{{ course.get_absolute_url }}">   
    def release_lessons(self):
        today = timezone.now().date()
        return self.lessons.filter(release_date__gte=today)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"
        ordering = ['name'] #-name : decrescente

class EnrollmentManager(models.Manager):
    
    def search(self, query): #realiza busca com base na string de entrada
        return self.get_queryset().filter(
            models.Q(course__icontains=query) | 
            models.Q(status__icontains=query) |
            models.Q(user__icontains=query) 
            )

class Enrollment(models.Model):

    STATUS_CHOICES = (
        (0,'Pendente'),(1,'Aprovado'),(2,'Cancelado'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="Usuário",
        related_name="enrollments",
        on_delete =models.DO_NOTHING 
    )
    course = models.ForeignKey(
        Courses, verbose_name="Curso", related_name="enrollments",
        on_delete=models.DO_NOTHING
    )
    status = models.IntegerField('Situação',
        choices=STATUS_CHOICES, default=0, blank=True
    )
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    objects = EnrollmentManager()

    def active(self):
        self.status = 1
        self.save()
    
    def is_approved(self):
        return self.status == 1

    class Meta:
        verbose_name= 'Inscrição'
        verbose_name_plural = 'Incrições'
        unique_together= ( ('user','course'), )
        #o unique_together define q só pode exister um conjunto unico
        #de usuario e curso, evitando repetições

class Announcement(models.Model):

    course = models.ForeignKey( Courses, on_delete=models.DO_NOTHING, 
        verbose_name='Curso', related_name='announcements')
    title = models.CharField( 'Título', max_length=100 )
    content = models.TextField('Conteúdo')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True) 

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Anúncio"
        verbose_name_plural = "Anúncios"
        ordering = ['-created_at']

class Comment(models.Model):

    announcement = models.ForeignKey(Announcement, verbose_name='Anúncio',
        on_delete=models.DO_NOTHING, related_name='comments'
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, 
                            verbose_name='usuário')
    comment = models.TextField('Comentário')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'
        ordering = ['created_at']

def post_save_announcement(instance, created, **kwargs):
    subject = instance.title
    context = {
        'announcement':instance,
    }
    template_name = 'courses/announcement_mail.html'
    enrollments = Enrollment.objects.filter(
        course=instance.course
    )
    for enrollment in enrollments:
        recipient_list = [enrollment.user.email]
        send_mail_template( subject, template_name, context, recipient_list )

models.signals.post_save.connect(
    post_save_announcement, sender=Announcement, dispatch_uid='post_save_announcement'
)

class Lesson(models.Model):

    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank = True)
    number = models.IntegerField('Número(ordem)', blank=True, default=0)
    release_date = models.DateField('Data de liberação', blank=True, null=True)

    course = models.ForeignKey(Courses, on_delete=models.DO_NOTHING,
        verbose_name='Curso', related_name='lessons')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.name

    def is_available(self):
        if self.release_date:
            today = timezone.now().date()
            return self.release_date >= today

    class Meta:
        verbose_name = "Aulas"
        verbose_name_plural = "Aulas"
        ordering = ['number']

class Material(models.Model):

    name = models.CharField('Nome', max_length=100)
    embedded = models.TextField('Vídeo Embutido(embedded)', blank=True)
    file = models.FileField('Arquivo', upload_to='lessons/materials',
        blank=True, null=True)
    
    lesson = models.ForeignKey(Lesson, on_delete=models.DO_NOTHING,
        verbose_name='aula', related_name='materials')

    def is_embedded(self):
        return bool(self.embedded)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name='Material'
        verbose_name_plural='Materiais'

simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from simplemooc.core.mail import send_mail_template
from .models import Comment

class ContactCourse(forms.Form):

    name = forms.CharField(label='Nome', max_length=100) 
    email = forms.EmailField(label= 'E-mail')
    message = forms.CharField(label='Mensagem/Duvida', widget=forms.Textarea)

    def send_mail(self, course):
        subject = '[%s] Contato' % course
        
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        template_name = 'courses/contact_email.html'
        send_mail_template(subject,template_name, context, [settings.CONTACT_EMAIL])

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['comment']

simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Courses, Enrollment, Announcement, Lesson, Material
from .forms import ContactCourse, CommentForm
from .decorator import enrollment_required

def index(request):
    courses = Courses.objects.all()
    template_name = "courses/index.html"

    context = {
        'courses':courses
    }

    return render(request, template_name, context)

def details(request, slug):
    #course = Courses.objects.get(pk=pk)
    #course = get_object_or_404(Courses, pk=pk)
    course = get_object_or_404(Courses, slug=slug)
    context = {}
    if request.method=="POST":
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid']='True'
            #form.send_mail(course)
            form.send_mail(course)
            print(form.cleaned_data)
            form = ContactCourse()            
    else:
        form = ContactCourse()

    context['course']= course
    context['form']= ContactCourse()
        
    template_name = 'courses/details.html'

    return render(request, template_name,context)

@login_required
def enrollment(request,slug)    :
    course = get_object_or_404(Courses, slug=slug)
    enrollment, created = Enrollment.objects.get_or_create(
        user=request.user, course=course
    )
    if created:
        enrollment.active()
        messages.success(request, "Você foi inscrito no curso com sucesso")
    else:
        messages.info(request, "Você já estava inscrito nesse curso")
    
    return redirect('accounts:dashboard')

@login_required
def undo_enrollment(request, slug):
    course = get_object_or_404(Courses, slug=slug)
    enrollment = get_object_or_404( Enrollment, 
            user=request.user, course=course
    )
    if request.method =="POST":
        enrollment.delete()
        messages.success(request, 'Sua inscrição foi cancelada com sucesso')
        return redirect('accounts:dashboard')
    template = "courses/undo_enrollment.html"
    context = {
        'enrollment': enrollment,
        'course': course,
    }
    return render(request, template, context)    

@login_required
@enrollment_required
def announcements(request, slug):
    course = request.course
    template = "courses/announcements.html"
    context = {
        'course': course,
        'announcements': course.announcements.all()
    }
    return render(request, template, context)

@login_required
@enrollment_required
def show_announcement(request, slug, pk):
    course = request.course
   
    announcement = get_object_or_404(course.announcements.all(), pk=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.announcement = announcement
        comment.save() 
        form = CommentForm()
        messages.success(request, 'Seu comentário foi enviado com sucesso')

    template = 'courses/show_announcement.html'
    

    context = {
        'course': course,
        'announcement': announcement,
        'form': form,
    }

    return render(request, template, context)

@login_required
@enrollment_required
def lessons(request, slug):
    course = request.course
    template = 'courses/lessons.html'
    lessons = course.release_lessons()    
    if request.user.is_staff:
        lessons = course.lessons.all()
    context = {
        'course': course,
        'lessons': lessons
    }
    return render(request,template,context)

@login_required
@enrollment_required
def lesson(request, slug, pk):
    course = request.course
    lesson = get_object_or_404(Lesson, pk=pk, course=course)
    # if not request.user.is_staff and not lesson.is_available():
    #     messages.error(request, 'Aula nao disponível')
    #     return redirect('courses:lessons', slug=course.slug)
    template = 'courses/lesson.html'
    context = {
        'course': course,
        'lesson': lesson
    }
    return render(request, template, context)

@login_required
@enrollment_required
def material(request, slug, pk):
    course = request.course
    material = get_object_or_404(Material, pk=pk, lesson__course=course)
    lesson = material.lesson

    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Material nao disponível')
        return redirect('courses:lesson', slug=course.slug, pk=lesson.pk)
    if not material.is_embedded():
        return redirect(material.file.url)
    template = 'courses/material.html'
    context = {
        'course':course,
        'lesson':lesson,
        'material':material,
    }

    return render(request, template, context)

simplemooc/courses/templates/courses/announcement_mail.html
{{ announcement.content|linebreaks }}

simplemooc/courses/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}


{% block dashboard_content %}
{% for announcement in announcements %}
    <div class="well">
        <h2><a href="{% url 'courses:show_announcement' course.slug announcement.pk %}"> 
            {{ announcement.title }}
        </a>            
        </h2>
        {{ announcement.content|linebreaks }}
        
        <p>
            <a href="{% url 'courses:show_announcement' course.slug announcement.pk %}#comments">
                <i class="fa fa-comments-o"></i>
                {% with comments_count=announcement.comments.count %}
                    {{ comments_count }} 
                    Comentário{{ comments_count|pluralize }}
                {% endwith %}
            </a>
        </p>
    </div>
{% empty %}
    <div class='well'>
        <h2>Nenhum anúncio criado</h2>
    </div>
{% endfor %}
    
{% endblock %}

simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemooc/courses/templates/courses/course_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{block.super}}
    <li> / </li>
    <li><a href="{% url 'courses:announcements'  course.slug %}"> {{course}} </a></li>

{% endblock %}

{% block menu_options %}
    <li class="pure-menu-heading">
        {{ course }}
    </li>
    <li>
        <a href="{% url 'courses:lessons' course.slug %}">
            <i class="fa fa-video-camera"></i>
            Aulas e Materiais
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-info-circle"></i>
            Informações
        </a>
    </li>
    <li>
        <a href="{% url 'courses:announcements' course.slug %}">
            <i class="fa fa-envelope"></i>
            Anúncios
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-comments"></i>
            Fórum de Dúvidas
        </a>
    </li>
    {{ block.super }}
{% endblock %}

simplemooc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="{%url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% for course in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ course.get_absolute_url }}">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="{{ course.name }}" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
            {{ course.description|linebreaks }}
        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum curso está disponível na plataforma</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/lesson.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    {{ lesson.description|linebreaks }}
    <p>
        <h4>Material da Aula</h4>
        <table class="pure-table full">
            <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        Ação
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for material in lesson.materials.all %}
                <tr class="{% cycle '' 'pure-table-odd' %}">
                    <td>
                        {{ material }}
                    </td>
                    <td>
                        {% if material.is_embedded %}
                        <a href="{% url 'courses:material' course.slug material.pk %}">
                            <i class"fa fa-video-camera"></i>
                            Acessar
                        </a>
                        {% else %}
                        <a target="_blank" href="{{ material.file.url }}">
                            <i class"fa fa-download"></i>
                            Baixar
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>
{% endblock %}

simplemooc/courses/templates/courses/lessons.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
{% endblock %}

{% block dashboard_content %}
{% for lesson in lessons %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    <p>
        {{ lesson.description|truncatewords:'20' }}
        <br />
        <a href="{% url 'courses:lesson' course.slug lesson.pk %}" title="">
        <i class="fa fa-eye"></i>
        Acessar Aula
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>
        Nenhuma aula disponível.
    </h2>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/material.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></h2>
    {{ material.embedded|safe }}
    <p>
        <a href="{% url 'courses:lesson' course.slug lesson.pk %}">Voltar</a>
    </p>
</div>
{% endblock %}

simplemooc/courses/templates/courses/show_announcement.html
{% extends 'courses/course_dashboard.html' %}

{% block breadcrumb %}
    {{block.super}}
    <li> / </li>
    <li><a href="{% url 'courses:show_announcement'  course.slug announcement.pk %}">Anúncio: {{announcement}}</a></li>
{% endblock %}

{% block dashboard_content %}
    <div class="well">
        <h2>{{ announcement.title}}</h2>
        {{ announcement.content|linebreaks }}        
    </div>
    <div class="well">
        <h4 id="comments">Comentários
            <a class="fright" href="#add_comment"><br>Comentar</a>
        </h4>
        <hr />
        {% for comment in announcement.comments.all %}
        <p>
            <strong>{{ comment.user }}</strong> disse à {{ comment.created_at|timesince }} atrás: <br />
            {{ comment.comment|linebreaksbr }}
        </p>
        <hr />
        {% empty %}
        <p>
            Nenhum comentário neste anúncio.
        </p>
        {% endfor %}
        
        <form method="post" class="pure-form pure-form-stacked" id="add_comment">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{field}}
                    {{field.errors}}                    
                    <!--<label for="password">Comentário</label>
                    <textarea cols="40" rows="4"></textarea>-->
                </div>

                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

simplemooc/courses/templates/courses/show_announcements.html
{% extends 'courses/course_dashboard.html' %}

{% block dashboard_content %}
    <div class="well">
        <h2>{{ announcement.title}}</h2>
        {{ announcement.content|linebreaks }}
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
    </div>
    <div class="well">
        <h4 id="comments">Comentários
        <a class="fright" href="#add_comment">Comentar</a></h4>
        <hr />
        <p>
            <strong>Fulano de Tal</strong> disse à 4 dias atrás: <br />
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua.
        </p>
        <hr />
        <p>
            <strong>Fulano de Tal</strong> disse à 2 dias atrás: <br />
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua.
        </p>
        <hr>
        <form method="post" class="pure-form pure-form-stacked" id="add_comment">
            <fieldset>
                <div class="pure-control-group">
                    <label for="password">Comentário</label>
                    <textarea cols="40" rows="4"></textarea>
                </div>

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

simplemooc/courses/templates/courses/undo_enrollment.html
{% extends 'courses/course_dashboard.html' %}

{% block dashboard_content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>
        Deseja realmente cancelar a inscrição do curso?
    </h3>
    <div class="pure-controls">
        <button type="submit" class="pure-button button-error">Confirmar</button>

        <a href="{% url 'courses:announcements' course.slug %}" 
            class="pure-button button-secondary">
            Voltar</a>

    </div>

</form>


{% endblock %}