simplemooc/accounts/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('entrar/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('sair/', auth_views.LogoutView.as_view(next_page='core:home'), name='logout'),
    path('registrar/', views.register, name='register'),
    path('registrar/', views.register, name='register'),
    path('editar/', views.edit, name='edit'),
    path('editar_senha/', views.edit_password, name='edit_password'),
    path('reset_senha', views.password_reset, name='password_reset'),
    re_path(r'^confirmar_senha/(?P<key>\w+)/$', views.password_reset_confirm, name='password_reset_confirm'),
]

simplemooc/courses/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    #re_path(r'^(?P<pk>\d+)/$', views.details, name='details'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
    re_path(r'^(?P<slug>[\w_-]+)/inscricao$', views.enrollment, name='enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/cancelar_inscricao$', views.undo_enrollment, 
        name='undo_enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios$', views.announcements, name='announcements'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$', views.show_announcement, name='show_announcement'),
    re_path(r'^(?P<slug>[\w_-]+)/aulas/$', views.lessons, name='lessons'),
    re_path(r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$', views.lesson, name='lesson'),
    re_path(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simplemooc.core.urls') ),
    path('cursos/', include('simplemooc.courses.urls') ),
    path('conta/', include('simplemooc.accounts.urls')),
    path('forum/', include('simplemooc.forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT  )

simplemooc/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.conf import settings
#from django.db.models.deletion 
#   import CASCADE, DO_NOTHING,SET,SET_DEFAULT,SET_NULL,PROTECT

import re
from django.core import validators

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField('Nome de Usuário', 
        max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile(r'^[\w.@+-]+$'),
        'Nome de usuario invalido, só pode conter @/./+/-/','invalid')]
        )
    email = models.EmailField('E-Mail', unique =True)
    first_name = models.CharField('Primeiro Nome', max_length=100, blank=True)
    last_name = models.CharField('Ultimo Nome', max_length=100, blank=True)
    #name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff= models.BooleanField('É da equipe', blank=True, default=False)
    date_joined = models.DateTimeField('Data de entrada', auto_now_add=True, editable=False)

    objects = UserManager()

    USERNAME_FIELD = 'username' #campo que será unico
    REQUIRED_FIELDS = ['email'] #necessario para criaçao de superuser

    def __str__(self):
        return self.first_name or self.username
    
    def get_short_name(self):
        return self.username
    
    def get_full_name(self):
        return self.first_name+" "+self.last_name or "Nao informado"

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class PasswordReset(models.Model):
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,#Cascade deleta tudo relacionado ao usuario
        verbose_name='Usuário', 
        related_name="resets"
        )

    key = models.CharField("Chave", max_length=100, unique=True)
    created_at = models.DateTimeField("Criado em", auto_now_add=True)
    confirmed = models.BooleanField("Confirmado?", default=False, blank=True)

    def __str__(self):
        return "{0} em {1}".format(self.user, self.created_at)
    
    class Meta:
        verbose_name = "Nova Senha"
        verbose_name_plural = "Novas Senhas"
        ordering = ['-created_at']

simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from simplemooc.core.mail import send_mail_template
from simplemooc.core.utils import generate_hash_key

from .models import PasswordReset

User = get_user_model()

class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='E-Mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError(
            'Nenhum usuário com este e-mail'
        ) 
    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key,user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Criar nova senha no Simple Mooc'
        context = {'reset':reset,}
        send_mail_template(subject, template_name, context, [user.email])

class RegisterForm(UserCreationForm):

    #email = forms.EmailField(label="E-Mail") #desnecessario pois já está no fields
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de Senha', widget=forms.PasswordInput)
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                'A confirmação de senha nao está correta',
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        #user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data['password1'])
                
        if commit:
            user.save()
        return user
    
    class Meta:
        model = User
        fields = ['username', 'email']

class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        #fields eh uma lista com os campos a serem alterados
        fields = ['username','email','first_name','last_name']

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import authenticate, login, get_user_model
from django.conf import settings
#from django.views.generic import 
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from simplemooc.core.utils import generate_hash_key
from simplemooc.courses.models import Enrollment
from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset

User = get_user_model()

@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    context['enrollments'] = Enrollment.objects.filter(user=request.user)

    return render(request, template_name, context)

def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(username=user.username,
                password=form.cleaned_data["password1"])

            login(request, user)    
            return redirect('core:home')
    else:
        form = RegisterForm()
    
    context = {
        'form': form,
    }
    return render( request, template_name, context )

def password_reset(request):

    template_name = 'accounts/password_reset.html'
    form = PasswordResetForm(request.POST or None)
    #com o POST or None o erro apenas será mostrado ao tentar Enviar
    context = {}
    if form.is_valid():
        # user = User.objects.get(email=form.cleaned_data['email'])
        # key = generate_hash_key(user.username)
        # reset = PasswordReset(key=key, user=user)
        # reset.save()
        form.save()        
        context['success']=True        
    context['form'] = form
    
    return render(request, template_name, context)

def password_reset_confirm(request, key):

    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success']= True
    context['form'] = form
    return render(request, template_name, context)

@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    form = EditAccountForm
    context = {}
    
    if request.method == 'POST':
        form = EditAccountForm( request.POST, instance=request.user )
        if form.is_valid:
            form.save()
            messages.success(request, "Os dados da sua conta foram editados")
            #form = EditAccountForm(instance=request.user)
            #context['success'] = True
            return redirect('accounts:dashboard')
    else:
        form = EditAccountForm( instance=request.user )
    context['form'] = form
    
    return render(request, template_name, context)

def edit_password(request):
    template_name='accounts/edit_password.html'
    context = {}

    if request.method =='POST':
        form = PasswordChangeForm(data=request.POST, user =request.user)
        if form.is_valid():
            form.save
            context['success'] = True
    else:
        form = PasswordChangeForm( user =request.user)

    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}

{% block content %}
{% load_my_courses user as enrollments %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Bem-vindo {{ user }}
                </li>
                
                {% block menu_options %}
                
                <li class="pure-menu-heading">Meus Cursos</li>
                    {% for enrollment in enrollments %}
                        <li>
                            <a href="{% url 'courses:announcements' enrollment.course.slug %}"> 
                            <i class="fa fa-book"></i></i>
                            {{ enrollment.course }} 
                            </a> 
                        </li>                
                    {% empty %}
                        <li>Você não é aluno de nenhum curso</li>
                    {% endfor %}

                <!-- {% my_courses user %} -->
                <!-- Dessa forma usar o inclusion_tag que importa do arquivo: 
                    templates/courses/templatetags/my_courses.html-->
                <li class="pure-menu-heading">Minha Conta</li>
                <li>
                    <a 
                        href="{% url 'accounts:edit' %}">
                        <i class="fa fa-cog" aria-hidden="true"></i>
                        Editar Conta
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:edit_password' %}">
                    <i class="fa fa-lock"></i>
                    Editar Senha
                    </a>
                </li>
                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <h2>Meus Cursos </h2>
            {% for enrollment in enrollments %}
                <div class="well">
                    <h3>{{ enrollment.course }}
                        ({{ enrollment.course.start_date|date:'d/m/Y'|default:'Sem Data de Início Informada' }})
                    </h3>
                    {{ enrollment.course.description|linebreaks }}
                    <div class="pure-controls">
                        <a href="{% url 'courses:announcements' enrollment.course.slug%}" 
                            class="pure-button pure-button-primary">Acessar</a>
                        <a href="{% url 'courses:undo_enrollment'  enrollment.course.slug%}" class="pure-button button-error">Cancelar</a>
                    </div>
                </div>
                {% empty %}
                <aside class="pure-u-1">
                    <p> Nenhum curso inscrito </p>
                </aside>
            {% endfor %}
            <!--
            <p><strong>Usuário</strong>: {{ user }}</p>
            <p><strong>Nome Completo</strong>: {{ user.get_full_name }}</p>
            <p><strong>E-mail</strong>: {{ user.email }}</p>
            -->
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Salvar Modificações</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Um e-mail foi enviando para você com mais detalhes de como criar uma nova senha</p>
        {% else %}
        <h2>Informe seu E-mail</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Sua senha foi criada com sucesso</p>
        {% else %}
        <h2>Informe sua nova Senha</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<p>Para criar uma nova senha, acesse o link: <a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key %}" title="Link para Criar Nova Senha">Criar Nova Senha</a></p>
<p>Reset Key: /conta/confirmar_senha/{{reset.key}} </p>>

simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}