simplemooc/core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('contato/', views.contact, name='contact'),
]

simplemooc/forum/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^tag/(?P<tag>[\w_-]+)$', views.index, name='index_tagged'),
    re_path(r'^(?P<slug>[\w_-]+)$', views.thread, name='thread'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simplemooc.core.urls') ),
    path('cursos/', include('simplemooc.courses.urls') ),
    path('conta/', include('simplemooc.accounts.urls')),
    path('forum/', include('simplemooc.forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT  )

simplemooc/forum/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager

from django_extensions.db.fields import AutoSlugField
from django.urls import reverse


class Thread(models.Model):

    title = models.CharField('Título', max_length=100)
    slug = models.SlugField('Identificador', max_length=100, unique=True)
    #slug = AutoSlugField('Identificador', max_length=100, unique=True, populate_from='title' )

    body = models.TextField('Mensagem')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
        verbose_name ='Autor', related_name='threads'
    )
    views = models.IntegerField('Visualizações', blank=True, default=0)
    answers = models.IntegerField('Respostas', blank=True, default=0)
    tags = TaggableManager()

    created_at = models.DateTimeField('Criado em:',auto_now_add=True )
    modified = models.DateTimeField('Modificado em:',auto_now=True )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forum:thread',args=[self.slug] )
    

    class Meta:
        verbose_name='Tópico'
        verbose_name_plural = 'Tópicos'
        ordering = ['-modified']
    
class Reply(models.Model):

    thread = models.ForeignKey(
        Thread, on_delete=models.DO_NOTHING,
        verbose_name='Tópico', related_name='replies'
    )
    reply = models.TextField('Resposta')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
        verbose_name ='Autor', related_name='replies'
    )
    correct = models.BooleanField('Correta?', blank=True, default=False)

    created_at = models.DateTimeField('Criado em:',auto_now_add=True )
    modified = models.DateTimeField('Modificado em:',auto_now=True )

    def __str__(self):
        return self.reply[:100]
    
    class Meta:
        verbose_name= 'Resposta'
        verbose_name_plural= 'Respostas'
        ordering = ['correct','created_at']

def post_save_reply(created_at, instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save() 
    # if created_at:
    #     instance.thread.answers = instance.thread.answers + 1
    #     instance.thread.save()

def post_delete_reply(instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    #instance.thread.answers = instance.thread.answers - 1
    instance.thread.save()

models.signals.post_save.connect(
    post_save_reply, sender=Reply, dispatch_uid='post_save_reply'
)
models.signals.post_delete.connect(
    post_delete_reply, sender=Reply, dispatch_uid='post_delete_reply'
)

simplemooc/forum/forms.py
from django import forms
from .models import Reply

class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['reply']

simplemooc/forum/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View, ListView, DetailView
from django.contrib import messages

from .models import Thread
from .forms import ReplyForm

# Create your views here.

# class ForumView(View):
#     def get(self, request, *args, **kwargs): #herdando View
#         return render(request, 'forum/index.html')

#class ForumView(TemplateView):
    #template_name = 'forum/index.html' #herdando TemplateView

class ForumView(ListView):
    #model = Thread
    paginate_by = 2
    template_name = 'forum/index.html'

    def get_queryset(self):
        queryset = Thread.objects.all()
        order = self.request.GET.get('order', '')
        #order = self.request.GET['order']
        if order == 'views':
            queryset = queryset.order_by('-views')
        elif order =='answers':
            queryset = queryset.order_by('-answers')       
        
        tag = self.kwargs.get('tag','')#pega tag, se nao passa ''(nada)
        if tag:
            queryset = queryset.filter(tags__slug__icontains=tag)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ForumView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        return context

class ThreadView(DetailView):

    model = Thread
    template_name = 'forum/thread.html'

    def get(self, request, *args, **kwargs):
        response = super(ThreadView, self).get(request, *args, **kwargs)
        if self.request.user.is_authenticated or (self.object.author != self.request.user):
            self.object.views = self.object.views + 1
            self.object.save()
        return response

    def get_context_data(self, **kwargs):
        context = super(ThreadView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        context['form'] = ReplyForm(self.request.POST or None)
        return context
    
    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(self.request, 'Para responder você deve estar logado')
            return redirect(self.request.path)
        self.object = self.get_object()
        context = self.get_context_data(object = self.object)
        form = context['form']
        if form.is_valid():
            reply = form.save(commit=False)
            reply.thread = self.object
            reply.author = self.request.user
            reply.save()
            message.success(self.request,'A reposta foi enviada com sucesso')
        return self.render_to_response(context)

index = ForumView.as_view()
#index = TemplateView.as_view(template_name='forum/index.html')
thread = ThreadView.as_view()

simplemooc/forum/templates/forum/index.html
{% extends "base.html" %}

<head>
    <meta charset="utf-8">
</head>

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:home' %}">Início</a></li>
            <li>/</li>
            <li><a href="{% url 'forum:index' %}">Fórum de Discussões</a></li>
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Tópicos do Fórum
                </li>
                <li>
                    <a href="?order=">
                        <i class="fa fa-refresh"></i>
                        Mais Recentes
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        Mais Visualizados
                    </a>
                </li>
                <li>
                    <a href="?order=answers">
                        <i class="fa fa-comments-o"></i>
                        Mais Comentados
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% for thread in object_list %}
            <div class="well">
                <h3><a href="{{thread.get_absolute_url}}" title="">{{ thread.title }}</a></h3>
                <h5>
                    Criado por {{ thread.author }} | {{ thread.answers }} 
                    resposta{{ thread.answers|pluralize }} | {{ thread.views }} 
                    Visualizaç{{ thread.views|pluralize:"ão,ões" }} 
                </h5>
                <p>
                    <i class="fa fa-tags"></i>
                    Tags: 
                    {% for tag in thread.tags.all %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" 
                        title="">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                    <a class="fright" href="{{ thread.get_absolute_url }}" title="">Atualizado há {{ thread.modified|timesince }} atrás</a>
                </p>
            </div>
            {% endfor %}
            <ul class="pagination pagination-centered">
                {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Anterior</a>
                </li>
                {% endif %}
                {% for page in paginator.page_range %}
                <li{% if page == page_obj.number %} class="active"{% endif %}>
                    <a href="?page={{ page }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">{{ page }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Próxima</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

simplemooc/forum/templates/forum/thread.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:home' %}">Início</a></li>
            <li>/</li>
            <li><a href="{% url 'forum:index' %}">Fórum de Discussões</a></li>
            <li>/</li>
            <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Tópicos do Fórum
                </li>
                <li>
                    <a href="?order=">
                        <i class="fa fa-refresh"></i>
                        Mais Recentes
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        Mais Visualizados
                    </a>
                </li>
                <li>
                    <a href="?order=answers">
                        <i class="fa fa-comments-o"></i>
                        Mais Comentados
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            <div class="well">
                <h2>{{ object }}</h2>
                {{ object.body|linebreaks }}
                <h5>
                    Criado por {{ object.author }}
                </h5>
                <p>
                    <i class="fa fa-tags"></i>
                    {% for tag in object.tags.all %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" title="">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                    <a class="fright" href="" title="">Criado a {{ object.created_at|timesince }} atrás</a>
                </p>
            </div>
            <div class="well" id="div-comments">
                <h4 id="comments">Respostas
                <a class="fright" href="#add_comment">Responder</a></h4>
                {% for reply in object.replies.all %}
                    <hr />
                    <p>
                        <strong>{{ reply.author }}</strong> disse à {{ reply.created_at|timesince }} atrás:
                        <br />
                        {{ reply.reply|linebreaksbr }}
                        <br />
                        {% if object.author == user %}
                        <!--
                        <a href="{% url 'forum:reply_incorrect' reply.pk %}" title="" class="pure-button button-error reply-cancel-correct-lnk{% if not reply.correct %} hidden{% endif %}">Cancelar Resposta Correta</a>

                        <a href="{% url 'forum:reply_correct' reply.pk %}" title="" class="pure-button button-success reply-correct-lnk{% if reply.correct %} hidden{% endif %}">Resposta Correta</a>
                        -->
                        <span class="fright label-success reply-correct-msg{% if not reply.correct %} hidden{% endif %}">resposta indicada pelo autor</span>
                        <br class="reply-correct-msg{% if not reply.correct %} hidden{% endif %}" />
                        {% elif reply.correct %}
                        <span class="fright label-success">resposta indicada pelo autor</span>
                        <br />
                        {% endif %}
                    </p>
                {% endfor %}
                <hr />
                <form method="post" class="pure-form pure-form-stacked" id="add_comment">
                    <fieldset>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% endfor %}
                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(".reply-cancel-correct-lnk").on("click", function(e){
        e.preventDefault();
        var $this = $(this);
        var $p = $this.closest("p");
        $.get($this.attr('href'), function(data){
            if(data.success){
                $p.find(".reply-correct-msg").addClass('hidden');
                $this.addClass('hidden');
                $p.find('.reply-correct-lnk').removeClass('hidden');
            } else {
                alert(data.message);
            }
        }, "json");
        return false;
    });
    $('.reply-correct-lnk').on('click', function(e){
        e.preventDefault();
        var $this = $(this);
        var $p = $this.closest("p");
        $.get($this.attr('href'), function(data){
            if(data.success){
                $("#div-comments .reply-correct-msg").addClass('hidden');
                $("#div-comments .reply-cancel-correct-lnk").addClass('hidden');
                $("#div-comments .reply-correct-lnk").removeClass('hidden');
                
                $p.find(".reply-correct-msg").removeClass('hidden');
                $this.addClass('hidden');
                $p.find('.reply-cancel-correct-lnk').removeClass('hidden');
            } else {
                alert(data.message)
            }
        }, 'json');
        return false;
    })
</script>
{% endblock %}